/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users/verifyOtp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/sendOtp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sendOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/resendOtp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resendOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/addUser": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/vocabulary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["generateVocabExercise"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/recording": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["receiveRecording"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/practice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["generateSpeakingPrompt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/listening": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["generateListeningAudio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/image-description/recording": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["receiveImageDescriptionRecording"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["generateExercise"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/generate-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["generateImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        VerifyOtpRequest: {
            /** Format: int32 */
            otp?: number;
            email?: string;
        };
        ApiResponseVoid: {
            success?: boolean;
            message?: string;
            data?: unknown;
        };
        SendOtpRequest: {
            email?: string;
        };
        RequestUserDto: {
            username?: string;
            password?: string;
            email?: string;
            roles?: string[];
        };
        ApiResponseResponseUserDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ResponseUserDto"];
        };
        ResponseUserDto: {
            /** Format: int32 */
            id?: number;
            username?: string;
            email?: string;
            roles?: string[];
            jwt?: string;
        };
        ExerciseRequestDto: {
            /** @enum {string} */
            level?: "A1" | "A2" | "B1";
            /** @enum {string} */
            topic?: "INTRODUCTION" | "FAMILY" | "HOME" | "FOOD_AND_DRINK" | "TIME_AND_DATES" | "DAILY_ROUTINE" | "WORK" | "SHOPPING" | "CLOTHES" | "HEALTH" | "SPORTS" | "HOBBIES" | "TRANSPORT" | "TRAVEL" | "WEATHER" | "NATURE" | "CITY_AND_PLACES" | "LUXEMBOURG" | "FRIENDS_AND_SOCIAL_LIFE" | "EVENTS_AND_CELEBRATIONS" | "PAST_EXPERIENCES" | "OPINIONS_AND_PREFERENCES" | "EDUCATION" | "PUBLIC_SERVICES" | "MEDIA_AND_TECHNOLOGY" | "FUTURE_PLANS";
            /** @enum {string} */
            type?: "TRANSLATION" | "MULTIPLE_CHOICE" | "FILL_IN_THE_BLANK" | "SHORT_ANSWER";
        };
        ApiResponseVocabularyDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["VocabularyDto"];
        };
        UsefulSentencesDto: {
            vocabularyWord?: string;
            wordTranslation?: string;
            sentence?: string;
            sentenceTranslation?: string;
        };
        VocabularyDto: {
            usefulSentences?: components["schemas"]["UsefulSentencesDto"][];
        };
        ApiResponseSpeakingEvaluation: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["SpeakingEvaluation"];
        };
        SpeakingEvaluation: {
            transcript?: string;
            /** Format: int32 */
            score?: number;
            feedback?: string;
            corrections?: string[];
        };
        ApiResponseSpeakingDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["SpeakingDto"];
        };
        SpeakingDto: {
            question?: string;
            type?: string;
            options?: string[];
            expectedAnswer?: string;
            hint?: string;
            questionTranslation?: string;
            hintTranslation?: string;
            /** Format: byte */
            audio?: string;
        };
        ApiResponseAudioExerciseDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["AudioExerciseDto"];
        };
        AudioExerciseDto: {
            question?: string;
            type?: string;
            options?: string[];
            expectedAnswer?: string;
            hint?: string;
            questionTranslation?: string;
            hintTranslation?: string;
            /** Format: byte */
            audio?: string;
        };
        ApiResponseGeneratedExerciseDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["GeneratedExerciseDto"];
        };
        GeneratedExerciseDto: {
            question?: string;
            type?: string;
            options?: string[];
            expectedAnswer?: string;
            hint?: string;
        };
        ApiResponseGeneratedImageDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["GeneratedImageDto"];
        };
        GeneratedImageDto: {
            /** Format: byte */
            image?: string;
            imageDescription?: string;
        };
        ApiResponseListResponseUserDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ResponseUserDto"][];
        };
        ApiResponseProgressDashboardDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ProgressDashboardDto"];
        };
        ProgressDashboardDto: {
            /** Format: int32 */
            userId?: number;
            username?: string;
            email?: string;
            /** Format: int32 */
            loggedInDays?: number;
            /** Format: int32 */
            currentStreakDays?: number;
            /** Format: date */
            lastLoginDate?: string;
            /** Format: int32 */
            totalActivities?: number;
            /** Format: int32 */
            evaluatedActivities?: number;
            /** Format: double */
            averageRatingOverall?: number;
            skillProgress?: components["schemas"]["SkillProgressDto"][];
        };
        SkillProgressDto: {
            exerciseType?: string;
            /** Format: int32 */
            totalActivities?: number;
            /** Format: int32 */
            evaluatedActivities?: number;
            /** Format: double */
            averageRatingOverall?: number;
            latestExerciseName?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    verifyOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyOtpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    sendOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendOtpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    resendOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendOtpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestUserDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseResponseUserDto"];
                };
            };
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestUserDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseResponseUserDto"];
                };
            };
        };
    };
    generateVocabExercise: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVocabularyDto"];
                };
            };
        };
    };
    receiveRecording: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    audio: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSpeakingEvaluation"];
                };
            };
        };
    };
    generateSpeakingPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSpeakingDto"];
                };
            };
        };
    };
    generateListeningAudio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAudioExerciseDto"];
                };
            };
        };
    };
    receiveImageDescriptionRecording: {
        parameters: {
            query: {
                imageDescription: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    audio: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSpeakingEvaluation"];
                };
            };
        };
    };
    generateExercise: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseGeneratedExerciseDto"];
                };
            };
        };
    };
    generateImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseGeneratedImageDto"];
                };
            };
        };
    };
    findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListResponseUserDto"];
                };
            };
        };
    };
    findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseResponseUserDto"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseResponseUserDto"];
                };
            };
        };
    };
    getMyProgress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProgressDashboardDto"];
                };
            };
        };
    };
}
