/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findById"];
        put: operations["updateUser"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put: operations["updateMe"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/prompts/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPrompt"];
        put: operations["updatePrompt"];
        post?: never;
        delete: operations["deletePrompt"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/exercise-config/types/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateType"];
        post?: never;
        delete: operations["deleteType"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/exercise-config/topics/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateTopic"];
        post?: never;
        delete: operations["deleteTopic"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/exercise-config/levels/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateLevel"];
        post?: never;
        delete: operations["deleteLevel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/verifyOtp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/sendOtp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sendOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/resendOtp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resendOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/resend-password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["forgotPassword_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/google-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["linkGoogle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/google-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["googleLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/addUser": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/exercises/{attemptId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeExercise"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["handleWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/subscription/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["checkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/vocabulary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["generateVocabExercise"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/recording": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["receiveRecording"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/practice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["generateSpeakingPrompt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/listening": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["generateListeningAudio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/image-description/recording": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["receiveImageDescriptionRecording"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["generateExercise"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/generate-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["generateImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPrompts"];
        put?: never;
        post: operations["createPrompt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/exercise-config/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/exercise-config/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createTopic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/exercise-config/levels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createLevel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateUserStatus"];
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/ai-quota": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["myAiQuota"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["searchLocations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercise-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getExerciseConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUser"];
        put?: never;
        post?: never;
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUserProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}/ai-usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUserAiUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}/ai-usage/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUserAiUsageSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}/ai-quota": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUserAiQuota"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/exercise-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getExerciseConfig_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RequestUserDto: {
            username?: string;
            password?: string;
            email?: string;
            firstName?: string;
            lastName?: string;
            street?: string;
            streetNumber?: string;
            postalCode?: string;
            city?: string;
            addressInfo?: string;
            roles?: string[];
        };
        ApiResponseResponseUserDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ResponseUserDto"];
        };
        ResponseUserDto: {
            /** Format: int32 */
            id?: number;
            username?: string;
            email?: string;
            firstName?: string;
            lastName?: string;
            street?: string;
            streetNumber?: string;
            postalCode?: string;
            city?: string;
            addressInfo?: string;
            emailVerified?: boolean;
            adminDisabled?: boolean;
            roles?: string[];
            subscription?: components["schemas"]["SubscriptionInfoDto"];
        };
        SubscriptionInfoDto: {
            subscribed?: boolean;
            status?: string;
            /** Format: date */
            startedAt?: string;
            /** Format: date */
            currentPeriodEnd?: string;
        };
        AdminPromptUpdateRequest: {
            title?: string;
            editableContent?: string;
            enabled?: boolean;
        };
        AdminPromptDto: {
            /** Format: int64 */
            id?: number;
            key?: string;
            title?: string;
            editableContent?: string;
            enabled?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ApiResponseAdminPromptDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["AdminPromptDto"];
        };
        AdminExerciseTypeConfigRequest: {
            code?: string;
            label: string;
            enabled?: boolean;
        };
        AdminExerciseTypeOptionDto: {
            code?: string;
            label?: string;
            enabled?: boolean;
        };
        ApiResponseAdminExerciseTypeOptionDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["AdminExerciseTypeOptionDto"];
        };
        AdminTopicConfigRequest: {
            code?: string;
            label: string;
            levelCode: string;
            enabled?: boolean;
        };
        AdminTopicOptionDto: {
            code?: string;
            label?: string;
            levelCode?: string;
            enabled?: boolean;
        };
        ApiResponseAdminTopicOptionDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["AdminTopicOptionDto"];
        };
        AdminLevelConfigRequest: {
            code?: string;
            label: string;
            description: string;
            enabled?: boolean;
        };
        AdminLevelOptionDto: {
            code?: string;
            label?: string;
            description?: string;
            enabled?: boolean;
        };
        ApiResponseAdminLevelOptionDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["AdminLevelOptionDto"];
        };
        VerifyOtpRequest: {
            /** Format: int32 */
            otp?: number;
            email?: string;
        };
        ApiResponseVoid: {
            success?: boolean;
            message?: string;
            data?: unknown;
        };
        SendOtpRequest: {
            email?: string;
        };
        ResetPasswordRequest: {
            /** Format: email */
            email: string;
            code: string;
            newPassword: string;
        };
        ForgotPasswordRequest: {
            /** Format: email */
            email: string;
        };
        GoogleLoginRequestDto: {
            idToken: string;
        };
        CompleteExerciseRequest: {
            learnerAnswer?: string;
        };
        ApiResponseExerciseAttemptDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ExerciseAttemptDto"];
        };
        ExerciseAttemptDto: {
            /** Format: int64 */
            id?: number;
            exerciseType?: string;
            exerciseName?: string;
            /** @enum {string} */
            status?: "GENERATED" | "COMPLETED" | "EVALUATED";
            level?: string;
            topic?: string;
            answerType?: string;
            learnerAnswer?: string;
            /** Format: double */
            averageRatingOverall?: number;
            /** Format: date-time */
            generatedAt?: string;
            /** Format: date-time */
            completedAt?: string;
            /** Format: date-time */
            evaluatedAt?: string;
        };
        ApiResponseStripeSessionURLDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["StripeSessionURLDto"];
        };
        StripeSessionURLDto: {
            stripeSessionUrl?: string;
        };
        VocabularyRequestDto: {
            level: string;
            topic: string;
        };
        ApiResponseVocabularyDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["VocabularyDto"];
        };
        UsefulSentencesDto: {
            vocabularyWord?: string;
            wordTranslation?: string;
            sentence?: string;
            sentenceTranslation?: string;
        };
        VocabularyDto: {
            /** Format: int64 */
            attemptId?: number;
            usefulSentences?: components["schemas"]["UsefulSentencesDto"][];
        };
        ApiResponseSpeakingEvaluation: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["SpeakingEvaluation"];
        };
        SpeakingEvaluation: {
            transcript?: string;
            /** Format: int32 */
            score?: number;
            feedback?: string;
            corrections?: string[];
        };
        ExerciseRequestDto: {
            level: string;
            topic: string;
            type: string;
        };
        ApiResponseSpeakingDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["SpeakingDto"];
        };
        SpeakingDto: {
            /** Format: int64 */
            attemptId?: number;
            question?: string;
            type?: string;
            options?: string[];
            expectedAnswer?: string;
            hint?: string;
            questionTranslation?: string;
            hintTranslation?: string;
            /** Format: byte */
            audio?: string;
        };
        ApiResponseAudioExerciseDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["AudioExerciseDto"];
        };
        AudioExerciseDto: {
            /** Format: int64 */
            attemptId?: number;
            question?: string;
            type?: string;
            options?: string[];
            expectedAnswer?: string;
            hint?: string;
            questionTranslation?: string;
            hintTranslation?: string;
            /** Format: byte */
            audio?: string;
        };
        ApiResponseGeneratedExerciseDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["GeneratedExerciseDto"];
        };
        GeneratedExerciseDto: {
            /** Format: int64 */
            attemptId?: number;
            question?: string;
            type?: string;
            options?: string[];
            expectedAnswer?: string;
            hint?: string;
        };
        ApiResponseGeneratedImageDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["GeneratedImageDto"];
        };
        GeneratedImageDto: {
            /** Format: int64 */
            attemptId?: number;
            /** Format: byte */
            image?: string;
            imageDescription?: string;
        };
        AdminPromptCreateRequest: {
            key: string;
            title?: string;
            editableContent?: string;
        };
        AdminUserStatusUpdateRequest: {
            adminDisabled: boolean;
            reason?: string;
        };
        AdminAiUsageSummaryDto: {
            /** Format: int32 */
            userId?: number;
            /** Format: int64 */
            totalRequests?: number;
            /** Format: int64 */
            totalInputTokens?: number;
            /** Format: int64 */
            totalOutputTokens?: number;
            /** Format: int64 */
            totalTokens?: number;
            totalEstimatedCostUsd?: number;
        };
        AdminUserDetailDto: {
            user?: components["schemas"]["ResponseUserDto"];
            progress?: components["schemas"]["ProgressDashboardDto"];
            aiUsage?: components["schemas"]["AdminAiUsageSummaryDto"];
            aiQuota?: components["schemas"]["AiQuotaStatusDto"];
        };
        AiQuotaCategoryStatusDto: {
            category?: string;
            window?: string;
            /** Format: int32 */
            limit?: number;
            /** Format: int64 */
            used?: number;
            /** Format: int64 */
            remaining?: number;
            /** Format: date-time */
            windowStart?: string;
            /** Format: date-time */
            windowEnd?: string;
        };
        AiQuotaStatusDto: {
            tier?: string;
            categories?: components["schemas"]["AiQuotaCategoryStatusDto"][];
        };
        ApiResponseAdminUserDetailDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["AdminUserDetailDto"];
        };
        ProgressDashboardDto: {
            /** Format: int32 */
            userId?: number;
            username?: string;
            email?: string;
            /** Format: int32 */
            loggedInDays?: number;
            /** Format: int32 */
            currentStreakDays?: number;
            /** Format: date */
            lastLoginDate?: string;
            /** Format: int32 */
            totalActivities?: number;
            /** Format: int32 */
            completedActivities?: number;
            /** Format: int32 */
            evaluatedActivities?: number;
            /** Format: double */
            averageRatingOverall?: number;
            latestExerciseName?: string;
            skillProgress?: components["schemas"]["SkillProgressDto"][];
        };
        SkillProgressDto: {
            exerciseType?: string;
            /** Format: int32 */
            totalActivities?: number;
            /** Format: int32 */
            completedActivities?: number;
            /** Format: int32 */
            evaluatedActivities?: number;
            /** Format: double */
            averageRatingOverall?: number;
            latestExerciseName?: string;
        };
        ApiResponseListResponseUserDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ResponseUserDto"][];
        };
        ApiResponseAiQuotaStatusDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["AiQuotaStatusDto"];
        };
        ApiResponseListLocationSuggestionDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["LocationSuggestionDto"][];
        };
        LocationSuggestionDto: {
            id?: string;
            label?: string;
            layerName?: string;
        };
        ApiResponseProgressDashboardDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ProgressDashboardDto"];
        };
        ApiResponseExerciseConfigDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ExerciseConfigDto"];
        };
        ExerciseConfigDto: {
            levels?: components["schemas"]["LevelOptionDto"][];
            topics?: components["schemas"]["TopicOptionDto"][];
            exerciseTypes?: components["schemas"]["ExerciseTypeOptionDto"][];
        };
        ExerciseTypeOptionDto: {
            code?: string;
            label?: string;
        };
        LevelOptionDto: {
            code?: string;
            label?: string;
            description?: string;
        };
        TopicOptionDto: {
            code?: string;
            label?: string;
            levelCode?: string;
        };
        ApiResponsePageResponseDtoResponseUserDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PageResponseDtoResponseUserDto"];
        };
        PageResponseDtoResponseUserDto: {
            items?: components["schemas"]["ResponseUserDto"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalItems?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        AdminUserProgressDto: {
            /** Format: int64 */
            id?: number;
            exerciseType?: string;
            exerciseName?: string;
            status?: string;
            level?: string;
            topic?: string;
            answerType?: string;
            /** Format: double */
            averageRatingOverall?: number;
            /** Format: date-time */
            generatedAt?: string;
            /** Format: date-time */
            completedAt?: string;
            /** Format: date-time */
            evaluatedAt?: string;
        };
        ApiResponsePageResponseDtoAdminUserProgressDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PageResponseDtoAdminUserProgressDto"];
        };
        PageResponseDtoAdminUserProgressDto: {
            items?: components["schemas"]["AdminUserProgressDto"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalItems?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        AdminAiUsageDto: {
            /** Format: int64 */
            id?: number;
            provider?: string;
            model?: string;
            requestName?: string;
            /** Format: int32 */
            inputTokens?: number;
            /** Format: int32 */
            outputTokens?: number;
            /** Format: int32 */
            totalTokens?: number;
            usageUnit?: string;
            /** Format: int64 */
            usageAmount?: number;
            estimatedCostUsd?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        ApiResponsePageResponseDtoAdminAiUsageDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PageResponseDtoAdminAiUsageDto"];
        };
        PageResponseDtoAdminAiUsageDto: {
            items?: components["schemas"]["AdminAiUsageDto"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalItems?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        ApiResponseAdminAiUsageSummaryDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["AdminAiUsageSummaryDto"];
        };
        ApiResponseListAdminPromptDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["AdminPromptDto"][];
        };
        AdminExerciseConfigDto: {
            editable?: boolean;
            levels?: components["schemas"]["AdminLevelOptionDto"][];
            topics?: components["schemas"]["AdminTopicOptionDto"][];
            exerciseTypes?: components["schemas"]["AdminExerciseTypeOptionDto"][];
        };
        ApiResponseAdminExerciseConfigDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["AdminExerciseConfigDto"];
        };
        AdminAuditLogDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int32 */
            actorUserId?: number;
            /** Format: int32 */
            targetUserId?: number;
            targetType?: string;
            targetId?: string;
            action?: string;
            oldValue?: string;
            newValue?: string;
            reason?: string;
            /** Format: date-time */
            createdAt?: string;
            actorLabel?: string;
            targetLabel?: string;
            actionLabel?: string;
            changeSummary?: string;
        };
        ApiResponsePageResponseDtoAdminAuditLogDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PageResponseDtoAdminAuditLogDto"];
        };
        PageResponseDtoAdminAuditLogDto: {
            items?: components["schemas"]["AdminAuditLogDto"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalItems?: number;
            /** Format: int32 */
            totalPages?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseResponseUserDto"];
                };
            };
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestUserDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseResponseUserDto"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseResponseUserDto"];
                };
            };
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestUserDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseResponseUserDto"];
                };
            };
        };
    };
    getPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAdminPromptDto"];
                };
            };
        };
    };
    updatePrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminPromptUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAdminPromptDto"];
                };
            };
        };
    };
    deletePrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    updateType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminExerciseTypeConfigRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAdminExerciseTypeOptionDto"];
                };
            };
        };
    };
    deleteType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    updateTopic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminTopicConfigRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAdminTopicOptionDto"];
                };
            };
        };
    };
    deleteTopic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    updateLevel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminLevelConfigRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAdminLevelOptionDto"];
                };
            };
        };
    };
    deleteLevel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    verifyOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyOtpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    sendOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendOtpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    resendOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendOtpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    forgotPassword_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    linkGoogle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleLoginRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseResponseUserDto"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestUserDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseResponseUserDto"];
                };
            };
        };
    };
    googleLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleLoginRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseResponseUserDto"];
                };
            };
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestUserDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseResponseUserDto"];
                };
            };
        };
    };
    completeExercise: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CompleteExerciseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExerciseAttemptDto"];
                };
            };
        };
    };
    handleWebhook: {
        parameters: {
            query?: never;
            header: {
                "Stripe-Signature": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancelSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    checkout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseStripeSessionURLDto"];
                };
            };
        };
    };
    generateVocabExercise: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VocabularyRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVocabularyDto"];
                };
            };
        };
    };
    receiveRecording: {
        parameters: {
            query?: {
                durationSeconds?: number;
                attemptId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    audio: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSpeakingEvaluation"];
                };
            };
        };
    };
    generateSpeakingPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSpeakingDto"];
                };
            };
        };
    };
    generateListeningAudio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAudioExerciseDto"];
                };
            };
        };
    };
    receiveImageDescriptionRecording: {
        parameters: {
            query: {
                imageDescription: string;
                durationSeconds?: number;
                attemptId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    audio: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSpeakingEvaluation"];
                };
            };
        };
    };
    generateExercise: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseGeneratedExerciseDto"];
                };
            };
        };
    };
    generateImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseGeneratedImageDto"];
                };
            };
        };
    };
    getPrompts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListAdminPromptDto"];
                };
            };
        };
    };
    createPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminPromptCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAdminPromptDto"];
                };
            };
        };
    };
    createType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminExerciseTypeConfigRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAdminExerciseTypeOptionDto"];
                };
            };
        };
    };
    createTopic: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminTopicConfigRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAdminTopicOptionDto"];
                };
            };
        };
    };
    createLevel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminLevelConfigRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAdminLevelOptionDto"];
                };
            };
        };
    };
    updateUserStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUserStatusUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAdminUserDetailDto"];
                };
            };
        };
    };
    findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListResponseUserDto"];
                };
            };
        };
    };
    myAiQuota: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAiQuotaStatusDto"];
                };
            };
        };
    };
    searchLocations: {
        parameters: {
            query: {
                query: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListLocationSuggestionDto"];
                };
            };
        };
    };
    getMyProgress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProgressDashboardDto"];
                };
            };
        };
    };
    getExerciseConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExerciseConfigDto"];
                };
            };
        };
    };
    getUsers: {
        parameters: {
            query?: {
                search?: string;
                subscribed?: boolean;
                adminDisabled?: boolean;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageResponseDtoResponseUserDto"];
                };
            };
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAdminUserDetailDto"];
                };
            };
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    getUserProgress: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageResponseDtoAdminUserProgressDto"];
                };
            };
        };
    };
    getUserAiUsage: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                provider?: string;
                model?: string;
                from?: string;
                to?: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageResponseDtoAdminAiUsageDto"];
                };
            };
        };
    };
    getUserAiUsageSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAdminAiUsageSummaryDto"];
                };
            };
        };
    };
    getUserAiQuota: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAiQuotaStatusDto"];
                };
            };
        };
    };
    getExerciseConfig_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAdminExerciseConfigDto"];
                };
            };
        };
    };
    getAuditLogs: {
        parameters: {
            query?: {
                actorUserId?: number;
                targetUserId?: number;
                targetType?: string;
                targetId?: string;
                action?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageResponseDtoAdminAuditLogDto"];
                };
            };
        };
    };
}
